name: Deploy VitePress site to Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust Node.js version as needed

      - name: Install Dependencies
        run: |
          cd docs 
          npm install

      - name: Build with VitePress
        run: |
          cd docs
          npm run docs:build

      - name: Check Build Output
        run: |
          ls -l docs/.vitepress/dist  # Verify build output contents
          cat docs/.vitepress/dist/index.html  # Inspect HTML content for correct paths

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: vitepress-build
          path: docs/.vitepress/dist  # Adjust path to include `docs` if needed

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: vitepress-build
          path: dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: dist
