name: Deploy VitePress site to Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd docs  # Navigate to the docs directory where package-lock.json is located
          npm install

      - name: Build with VitePress
        run: |
          cd docs  # Navigate to the docs directory where package-lock.json is located
          npm run docs:build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: VitePress Build
          path: docs/.vitepress/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs/.vitepress/dist
